# Generated by Django 4.2.17 on 2025-01-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racerv2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('is_google_hosted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tracked_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='racerv2.trackedrequest')),
            ],
        ),
    ]
