# Generated by Django 4.2.17 on 2025-01-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerv2', '0004_merge_20250102_1519'),
    ]

    operations = [
    ]
