# Generated by Django 4.2.17 on 2025-01-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racerv2', '0005_group_remove_trackedrequest_hidden'),
        ('racerv2', '0006_remove_trackedrequest_hidden'),
    ]

    operations = [
    ]
