# Generated by Django 4.2.17 on 2025-01-03 03:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('geolocation', models.TextField(blank=True, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_hidden', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tracked Request',
                'verbose_name_plural': 'Tracked Requests',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True, null=True)),
                ('headers', models.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tracked_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_records', to='racerv2.trackedrequest')),
            ],
            options={
                'verbose_name': 'Connection Record',
                'verbose_name_plural': 'Connection Records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
