# Generated by Django 4.2.17 on 2025-01-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerv2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedrequest',
            name='relay_count',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
