# Generated by Django 4.2.17 on 2025-01-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerv2', '0002_trackedrequest_relay_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrecord',
            name='is_google_hosted',
            field=models.BooleanField(default=True),
        ),
    ]
