# Generated by Django 4.2.17 on 2025-01-02 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racerv2', '0002_connectionrecord'),
    ]

    operations = [


    ]
