# Generated by Django 4.2.17 on 2025-01-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racerv2', '0004_alter_connectionrecord_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedrequest',
            name='heat_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trackedrequest',
            name='relay_count',
            field=models.IntegerField(default=0),
        ),
    ]
