# Generated by Django 4.2.17 on 2025-01-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racerv2', '0007_merge_20250102_1557'),
        ('racerv2', 'fake'),
    ]

    operations = [
    ]
